from os import path

try:
    from .version import __version__
except ImportError:
    # version.py is generated by setuptools-scm at build/install time, so it is
    # absent when running straight out of a fresh clone (e.g. PYTHONPATH=source
    # with no install). Do not hardcode a real-looking number here: it would go
    # stale silently and misreport the version.
    __version__ = "0.0.0.dev0"
# ORDER IS LOAD-BEARING, DO NOT SORT. mm_funcs declares
# `class PointLensSFitFunction(sfit_minimizer.SFitFunction)`, which resolves at
# class-definition time, so sfit_classes must have populated this namespace
# first. Alphabetical order puts mm_funcs first and raises
# "partially initialized module ... has no attribute 'SFitFunction'".
# Enforced by per-file-ignores for I001 in pyproject.toml.
from sfit_minimizer.sfit_minimize import *
from sfit_minimizer.sfit_classes import *
from sfit_minimizer.mm_funcs import *

MODULE_PATH = path.abspath(__file__)
for i in range(3):
    MODULE_PATH = path.dirname(MODULE_PATH)

path_1 = path.join(MODULE_PATH, 'data')
if path.isdir(path_1):
    DATA_PATH = path_1
else:
    DATA_PATH = path.join(path.dirname(__file__), 'data')
