# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
import os
import sys

sys.path.insert(0, os.path.abspath("../../source/"))
print(sys.path)

# -- Project information -----------------------------------------------------

project = "SFit Minimizer"
copyright = "2021, Jennifer Yee"
author = "Jennifer Yee"

# The full version, including alpha/beta/rc tags.
#
# Read from the installed package rather than hardcoded -- it used to say "0",
# which was never updated across three releases. The version itself comes from
# the git tag via setuptools-scm, so tag -> package -> docs is one chain with
# nothing to remember. Requires the package to be installed, which it is under
# `uv run --extra docs`; the fallback keeps a bare `sphinx-build` in an
# uninstalled checkout from failing outright.
try:
    from importlib.metadata import version as _version

    release = _version("sfit_minimizer")
except Exception:
    release = "0.0.0.dev0"


# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = ["sphinx.ext.autodoc"]

# Add any paths that contain templates here, relative to this directory.
templates_path = ["_templates"]

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = []


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = "alabaster"

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
# Empty: this project ships no custom CSS/JS, and the output directory (docs/)
# is the PARENT of this source directory, so any path here resolves inside
# outdir and Sphinx warns about it. The docs/_static/ directory in the built
# output is generated by the theme, not copied from here.
html_static_path = []

# Output the documentation in the order it appears. Rather than
# alphabetically.
autodoc_member_order = "bysource"
